/*
 * initialize game state observers
 */
// let _p1PointsMem = new GameStatePropertyObserver( "_p1PointsMem" );
// let _p2PointsMem = new GameStatePropertyObserver( "_p2PointsMem" );
// let _p1GamesMem = new GameStatePropertyObserver( "_p1GamesMem" );
// let _p2GamesMem = new GameStatePropertyObserver( "_p2GamesMem" );
// let _p1SetsMem = new GameStatePropertyObserver( "_p1SetsMem" );
// let _p2SetsMem = new GameStatePropertyObserver( "_p2SetsMem" );
// let _toggle = new GameStatePropertyObserver( "_toggle" );
// let _tieBreakOnly = new GameStatePropertyObserver( "_tieBreakOnly" );
// let _p1Points = new GameStatePropertyObserver( "_p1Points" );
// let _p2Points = new GameStatePropertyObserver( "_p2Points" );
// let _p1Games = new GameStatePropertyObserver( "_p1Games" );
// let _p2Games = new GameStatePropertyObserver( "_p2Games" );
// let _p1Sets = new GameStatePropertyObserver( "_p1Sets" );
// let _p2Sets = new GameStatePropertyObserver( "_p2Sets" );
// let _prevP1Points = new GameStatePropertyObserver( "_prevP1Points" );
// let _prevP2Points = new GameStatePropertyObserver( "_prevP2Points" );
// let _prevP1Games = new GameStatePropertyObserver( "_prevP1Games" );
// let _prevP2Games = new GameStatePropertyObserver( "_prevP2Games" );
// let _prevP1Sets = new GameStatePropertyObserver( "_prevP1Sets" );
// let _prevP2Sets = new GameStatePropertyObserver( "_prevP2Sets" );
// let _prev1P1Points = new GameStatePropertyObserver( "_prev1P1Points" );
// let _prev1P2Points = new GameStatePropertyObserver( "_prev1P2Points" );
// let _prev1P1Games = new GameStatePropertyObserver( "_prev1P1Games" );
// let _prev1P2Games = new GameStatePropertyObserver( "_prev1P2Games" );
// let _prev1P1Sets = new GameStatePropertyObserver( "_prev1P1Sets" );
// let _prev1P2Sets = new GameStatePropertyObserver( "_prev1P2Sets" );
// let _prev2P1Points = new GameStatePropertyObserver( "_prev2P1Points" );
// let _prev2P2Points = new GameStatePropertyObserver( "_prev2P2Points" );
// let _prev2P1Games = new GameStatePropertyObserver( "_prev2P1Games" );
// let _prev2P2Games = new GameStatePropertyObserver( "_prev2P2Games" );
// let _prev2P1Sets = new GameStatePropertyObserver( "_prev2P1Sets" );
// let _prev2P2Sets = new GameStatePropertyObserver( "_prev2P2Sets" );
// let _prev3P1Points = new GameStatePropertyObserver( "_prev3P1Points" );
// let _prev3P2Points = new GameStatePropertyObserver( "_prev3P2Points" );
// let _prev3P1Games = new GameStatePropertyObserver( "_prev3P1Games" );
// let _prev3P2Games = new GameStatePropertyObserver( "_prev3P2Games" );
// let _prev3P1Sets = new GameStatePropertyObserver( "_prev3P1Sets" );
// let _prev3P2Sets = new GameStatePropertyObserver( "_prev3P2Sets" );
// let _p1Matches = new GameStatePropertyObserver( "_p1Matches" );
// let _p2Matches = new GameStatePropertyObserver( "_p2Matches" );
// let _prevP1Matches = new GameStatePropertyObserver( "_prevP1Matches" );
// let _prevP2Matches = new GameStatePropertyObserver( "_prevP2Matches" );
// let _prev1P1Matches = new GameStatePropertyObserver( "_prev1P1Matches" );
// let _prev1P2Matches = new GameStatePropertyObserver( "_prev1P2Matches" );
// let _prev2P1Matches = new GameStatePropertyObserver( "_prev2P1Matches" );
// let _prev2P2Matches = new GameStatePropertyObserver( "_prev2P2Matches" );
// let _prev3P1Matches = new GameStatePropertyObserver( "_prev3P1Matches" );
// let _prev3P2Matches = new GameStatePropertyObserver( "_prev3P2Matches" );
// let _tieLEDsOn = new GameStatePropertyObserver( "_tieLEDsOn" );
// let _prevTieLEDsOn = new GameStatePropertyObserver( "_prevTieLEDsOn" );
// let _prev1TieLEDsOn = new GameStatePropertyObserver( "_prev1TieLEDsOn" );
// let _prev2TieLEDsOn = new GameStatePropertyObserver( "_prev2TieLEDsOn" );
// let _prev3TieLEDsOn = new GameStatePropertyObserver( "_prev3TieLEDsOn" );
// let _setTieBreak = new GameStatePropertyObserver( "_setTieBreak" );
// let _prevSetTieBreak = new GameStatePropertyObserver( "_prevSetTieBreak" );
// let _prev1SetTieBreak = new GameStatePropertyObserver( "_prev1SetTieBreak" );
// let _prev2SetTieBreak = new GameStatePropertyObserver( "_prev2SetTieBreak" );
// let _prev3SetTieBreak = new GameStatePropertyObserver( "_prev3SetTieBreak" );
// let _tieBreak = new GameStatePropertyObserver( "_tieBreak" );
// let _prevTieBreak = new GameStatePropertyObserver( "_prevTieBreak" );
// let _prev1TieBreak = new GameStatePropertyObserver( "_prev1TieBreak" );
// let _prev2TieBreak = new GameStatePropertyObserver( "_prev2TieBreak" );
// let _prev3TieBreak = new GameStatePropertyObserver( "_prev3TieBreak" );
// let _serve = new GameStatePropertyObserver( "_serve" );
// let _prevServe = new GameStatePropertyObserver( "_prevServe" );
// let _prev1Serve = new GameStatePropertyObserver( "_prev1Serve" );
// let _prev2Serve = new GameStatePropertyObserver( "_prev2Serve" );
// let _prev3Serve = new GameStatePropertyObserver( "_prev3Serve" );
// let _pointFlash = new GameStatePropertyObserver( "_pointFlash" );
// let _prevPointFlash = new GameStatePropertyObserver( "_prevPointFlash" );
// let _prev1PointFlash = new GameStatePropertyObserver( "_prev1PointFlash" );
// let _prev2PointFlash = new GameStatePropertyObserver( "_prev2PointFlash" );
// let _prev3PointFlash = new GameStatePropertyObserver( "_prev3PointFlash" );
// let _started = new GameStatePropertyObserver( "_started" );
// let _gameStarted = new GameStatePropertyObserver( "_gameStarted" );
// let _rotaryPosition = new GameStatePropertyObserver( "_rotaryPosition" );
// let _prevRotaryPosition = new GameStatePropertyObserver( "_prevRotaryPosition" );
// let _playerButton = new GameStatePropertyObserver( "_playerButton" );
// let _undo = new GameStatePropertyObserver( "_undo" );
// let _rotaryChange = new GameStatePropertyObserver( "_rotaryChange" );
// let _now = new GameStatePropertyObserver( "_now" );
// let _previousTime = new GameStatePropertyObserver( "_previousTime" );
// let _updateDisplayDelay = new GameStatePropertyObserver( "_updateDisplayDelay" );
// let _buttonDelay = new GameStatePropertyObserver( "_buttonDelay" );
// let _flashDelay = new GameStatePropertyObserver( "_flashDelay" );
// let _gameFlashDelay = new GameStatePropertyObserver( "_gameFlashDelay" );
// let _tiePulseCount = new GameStatePropertyObserver( "_tiePulseCount" );
// let _gameWinPulseCount = new GameStatePropertyObserver( "_gameWinPulseCount" );
// let _setWinPulseCount = new GameStatePropertyObserver( "_setWinPulseCount" );
// let _matchWinPulseCount = new GameStatePropertyObserver( "_matchWinPulseCount" );
// let _serveSwitch = new GameStatePropertyObserver( "_serveSwitch" );
// let _setTieBreakMem = new GameStatePropertyObserver( "_setTieBreakMem" );
// let _tieBreakMem = new GameStatePropertyObserver( "_tieBreakMem" );

// let gsPropertySubject = new Subject();
// gsPropertySubject.addObserver( _p1Points );
// gsPropertySubject.addObserver( _p2Points );
// gsPropertySubject.addObserver( _p1Games );
// gsPropertySubject.addObserver( _p2Games );
// gsPropertySubject.addObserver( _p1Sets );
// gsPropertySubject.addObserver( _p2Sets );
// gsPropertySubject.addObserver( _p1Matches );
// gsPropertySubject.addObserver( _p2Matches );
// gsPropertySubject.addObserver( _tieLEDsOn );
// gsPropertySubject.addObserver( _setTieBreak );
// gsPropertySubject.addObserver( _tieBreak );
// gsPropertySubject.addObserver( _serve );
// gsPropertySubject.addObserver( _pointFlash );
// gsPropertySubject.addObserver( _started );
// gsPropertySubject.addObserver( _rotaryPosition );
// gsPropertySubject.addObserver( _playerButton );
// gsPropertySubject.addObserver( _undo );
// gsPropertySubject.addObserver( _rotaryChange );
// gsPropertySubject.addObserver( _now );
// gsPropertySubject.addObserver( _updateDisplayDelay );
// gsPropertySubject.addObserver( _buttonDelay );
// gsPropertySubject.addObserver( _flashDelay );
// gsPropertySubject.addObserver( _gameFlashDelay );
// gsPropertySubject.addObserver( _tiePulseCount );
// gsPropertySubject.addObserver( _gameWinPulseCount );
// gsPropertySubject.addObserver( _setWinPulseCount );
// gsPropertySubject.addObserver( _matchWinPulseCount );
// gsPropertySubject.addObserver( _serveSwitch );
// gsPropertySubject.addObserver( _setTieBreakMem );
// gsPropertySubject.addObserver( _tieBreakMem );
// gsPropertySubject.addObserver( _p1PointsMem );
// gsPropertySubject.addObserver( _p2PointsMem );
// gsPropertySubject.addObserver( _p1GamesMem );
// gsPropertySubject.addObserver( _p2GamesMem );
// gsPropertySubject.addObserver( _p1SetsMem );
// gsPropertySubject.addObserver( _p2SetsMem );
// gsPropertySubject.addObserver( _prevP1Points );
// gsPropertySubject.addObserver( _prevP2Points );
// gsPropertySubject.addObserver( _prevP1Games );
// gsPropertySubject.addObserver( _prevP2Games );
// gsPropertySubject.addObserver( _prevP1Sets );
// gsPropertySubject.addObserver( _prevP2Sets );

GameState = require( "../GameState" );
let project_path = "C:\\Users\\EG\\Desktop\\2022\\april\\5th_week\\node-addon-examples\\6_object_wrap\\node-addon-api\\";
let game_state_path = project_path + "game_state_data\\game_state_data.txt"; 
let gameState = new GameState( game_state_path );

setInterval( () => { gameState.update(); }, 1000 );
